title: Clusters
modelClass: Initbiz\CumulusCore\Models\Cluster
list: $/initbiz/cumuluscore/models/cluster/columns.yaml
recordUrl: 'initbiz/cumuluscore/clusters/update/:cluster_id'
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
filter: config_filter.yaml
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
