# ===================================
#  Extended Profile Field Definitions
# ===================================

clusters:
    label: "Clusters"
    tab: "Clusters"
    type: relation
    nameFrom: full_name
