list: $/initbiz/cumuluscore/models/plan/columns.yaml
modelClass: Initbiz\CumulusCore\Models\Plan
title: initbiz.cumuluscore::lang.plan_list.title
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'initbiz/cumuluscore/plans/update/:id'
filter: config_filter.yaml
