list: $/initbiz/cumuluscore/models/plan/columns.yaml
modelClass: InitBiz\CumulusCore\Models\Plan
title: Plans
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'initbiz/cumuluscore/plans/update/:plan_id'
